using System;
using System.Configuration;
using System.Web;
using System.Web.SessionState;

/*
 * How To:
 * 1. Set up Portal as an IdP using the Intranet. (Must be performed by a Parature Technician)
 * 2. (This is performed by a Parature Technician) Set the :
 *  2a. ACS Url to the url of this website. This can be changed later. During testing it will likely be a localhost address
 *  2b. SP Id - Unique ID for this sso instance (department specific). 
 *      Likely never changes. Needs to be formatted as a URI, but is not used at all except in the below link
 * 3. Trigger an IdP initiated SSO:
 *  https://sso.parature.com/sp/startSSO.ping?PartnerIdpId={IdP-Url-fromParature}&TARGET={FinalUrlToLandOn}
 *      Where {IdP-Url-fromParature} is the "ssoIdPUrl" in the webconfig, and is provided by Parature
 *      And {FinalUrlToLandOn} can be dynamically generated by your server. 
 *          -> It specifies the location where our authentication server redirects to with the RefId token in the query string
 *      
 * This will kick off IdP initiated SSO and end at the {FinalUrlToLandOn}.
 */
namespace RefIdSP
{
    public class Global : HttpApplication
    {
        void Application_Start(object sender, EventArgs e)
        { }

        void Application_End(object sender, EventArgs e)
        { }

        void Application_BeginRequest(object sender, EventArgs e)
        {
            HttpContext.Current.SetSessionStateBehavior(SessionStateBehavior.Required);
        }

        void Application_PreRequestHandlerExecute(object sender, EventArgs e)
        {
            /*
             * If the query string has a "REF", it is a token to go pick up the Claims from the parature SSO server
             */
            var refId = Request.QueryString["REF"];
            if (string.IsNullOrEmpty(refId) == false)
            {
                //SSO settings to talk to the parature SSO server
                //A cert may be used instead of a username/password, but your cert must be signed by a trusted CA
                // -> This is out of scope of this code sample
                var username = ConfigurationManager.AppSettings["ssoUsername"];
                var password = ConfigurationManager.AppSettings["ssoPassword"];
                var instanceId = ConfigurationManager.AppSettings["ssoInstanceId"];

                //get the claims information. 
                //This requires a round-trip request from the parature SSO server
                var json = RefIdHelper.PickUp(refId, username, password, instanceId);
                //read a key from the JSON. This key may be different for your configuration
                var email = json.Value<string>("email"); //EXAMPLE ONLY
                if (email != null)
                {
                    SessionManager.Name = email;
                }
            }
        }

        void Application_Error(object sender, EventArgs e)
        { }
    }
}
